import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from app import app, db
from models import Task, User


TASKS = [
    {
        "title": "Заповніть профіль на 100%",
        "description": "Додайте основні дані профілю, щоб підвищити довіру.",
        "instructions": "Заповніть ім'я, телефон, email, країну/місто та короткий опис. У поданні напишіть, які поля заповнили.",
        "task_type": "custom",
        "category": "Onboarding",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за повне заповнення профілю.",
        "icon": "fa-user-check",
        "color": "#22c55e",
        "is_featured": True,
    },
    {
        "title": "Додайте аватар профілю",
        "description": "Профіль з аватаром виглядає більш надійно.",
        "instructions": "Завантажте аватар і надішліть скрін профілю.",
        "task_type": "custom",
        "category": "Onboarding",
        "reward_type": "xp",
        "reward_amount": 100,
        "reward_description": "XP за персоналізацію профілю.",
        "icon": "fa-user-circle",
        "color": "#38bdf8",
        "is_featured": True,
    },
    {
        "title": "Увімкніть 2FA для безпеки",
        "description": "Захистіть акаунт двофакторною аутентифікацією.",
        "instructions": "Увімкніть 2FA у налаштуваннях та надішліть скрін підтвердження.",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "subscription",
        "reward_amount": 3,
        "reward_description": "3 дні підписки за підвищення безпеки.",
        "icon": "fa-shield-alt",
        "color": "#f59e0b",
        "is_featured": True,
    },
    {
        "title": "Підключіть біржу через API",
        "description": "Підключіть свою біржу, щоб почати копі-трейдинг.",
        "instructions": "Додайте API ключі біржі з правами торгівлі. Надішліть скрін підключення.",
        "task_type": "trading",
        "category": "Onboarding",
        "reward_type": "xp",
        "reward_amount": 250,
        "reward_description": "XP за успішне підключення біржі.",
        "icon": "fa-link",
        "color": "#0ea5e9",
        "is_featured": True,
    },
    {
        "title": "Увімкніть Telegram-сповіщення",
        "description": "Отримуйте миттєві оновлення по угодах.",
        "instructions": "Підключіть Telegram-бота, введіть Chat ID та увімкніть сповіщення.",
        "task_type": "community",
        "category": "Onboarding",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за підключення Telegram.",
        "icon": "fa-bell",
        "color": "#60a5fa",
        "is_featured": True,
    },
    {
        "title": "Пройдіть чекліст безпеки",
        "description": "Перевірте, що ваші API ключі налаштовані правильно.",
        "instructions": "Підтвердіть: лише trading permissions, без withdrawals, IP whitelist. Напишіть у поданні «Готово».",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за дотримання безпеки.",
        "icon": "fa-lock",
        "color": "#f97316",
    },
    {
        "title": "Прочитайте FAQ та дайте відповідь",
        "description": "Швидке знайомство з ключовими правилами.",
        "instructions": "Прочитайте FAQ та відповідайте: «Який мінімальний вік користувача?»",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за ознайомлення з FAQ.",
        "icon": "fa-book-open",
        "color": "#a855f7",
    },
    {
        "title": "Приєднайтесь до Telegram-спільноти",
        "description": "Будьте в курсі новин і оновлень.",
        "instructions": "Приєднайтесь до офіційного каналу/чату та надішліть скрін з вашим username.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за вступ у спільноту.",
        "icon": "fa-telegram",
        "color": "#0ea5e9",
    },
    {
        "title": "Запросіть 1 друга",
        "description": "Почніть розвивати свою мережу.",
        "instructions": "Запросіть друга за реферальним посиланням і надішліть його username.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 5,
        "reward_description": "$5 бонусу за перший реферал.",
        "icon": "fa-user-plus",
        "color": "#22c55e",
        "is_featured": True,
    },
    {
        "title": "Запросіть 3 друзів",
        "description": "Малий реферальний челендж.",
        "instructions": "Запросіть 3 друзів. У поданні перерахуйте їх usernames.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 15,
        "reward_description": "$15 бонусу за 3 рефералів.",
        "icon": "fa-users",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 5 друзів",
        "description": "Реферальний рівень PRO.",
        "instructions": "Запросіть 5 друзів. Додайте список username рефералів.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "subscription",
        "reward_amount": 7,
        "reward_description": "7 днів підписки за 5 рефералів.",
        "icon": "fa-users",
        "color": "#8b5cf6",
    },
    {
        "title": "Запросіть 10 друзів",
        "description": "Вийдіть на новий рівень росту.",
        "instructions": "Запросіть 10 друзів і надішліть їх usernames.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 50,
        "reward_description": "$50 бонусу за 10 рефералів.",
        "icon": "fa-users",
        "color": "#14b8a6",
    },
    {
        "title": "Запросіть 1 активного трейдера",
        "description": "Запросіть друга, який зробить хоча б одну угоду.",
        "instructions": "Запросіть друга та надішліть його username після першої угоди.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 10,
        "reward_description": "$10 за активного реферала.",
        "icon": "fa-user-check",
        "color": "#22c55e",
    },
    {
        "title": "Поділіться реферальним посиланням у соцмережі",
        "description": "Публікація у вашому профілі (з чесним дисклеймером).",
        "instructions": "Опублікуйте пост із реферальним посиланням і дисклеймером. Надішліть лінк.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за поширення посилання.",
        "icon": "fa-share-alt",
        "color": "#38bdf8",
        "is_featured": True,
    },
    {
        "title": "Поділіться реферальним посиланням у Telegram-чаті",
        "description": "Поширте посилання у релевантному чаті.",
        "instructions": "Поділіться посиланням у тематичному чаті без спаму. Надішліть скрін або лінк.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за поширення у спільноті.",
        "icon": "fa-paper-plane",
        "color": "#0ea5e9",
    },
    {
        "title": "Опублікуйте відгук про MIMIC",
        "description": "Поділіться враженнями про платформу.",
        "instructions": "Залиште відгук у соцмережі або на форумі та надішліть лінк.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "goods",
        "reward_amount": 10,
        "reward_description": "Бонусний бейдж/стікер пак.",
        "icon": "fa-comment-dots",
        "color": "#f97316",
        "max_participants": 300,
    },
    {
        "title": "Запишіть коротке відео-відгук",
        "description": "Відео 30-60 секунд про ваш досвід.",
        "instructions": "Запишіть відео-відгук і надішліть посилання (можна приватно).",
        "task_type": "community",
        "category": "Community",
        "reward_type": "goods",
        "reward_amount": 25,
        "reward_description": "Мерч або подарунковий сертифікат.",
        "icon": "fa-video",
        "color": "#f43f5e",
        "max_participants": 100,
    },
    {
        "title": "Зробіть першу угоду",
        "description": "Почніть торговий шлях.",
        "instructions": "Зробіть першу угоду та надішліть скрін історії.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 300,
        "reward_description": "XP за першу угоду.",
        "icon": "fa-bolt",
        "color": "#22c55e",
        "is_featured": True,
    },
    {
        "title": "Зробіть 5 угод",
        "description": "Закріпіть навичку.",
        "instructions": "Зробіть 5 угод і надішліть скрін статистики.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 5,
        "reward_description": "$5 бонусу за 5 угод.",
        "icon": "fa-chart-line",
        "color": "#22c55e",
    },
    {
        "title": "Зробіть 10 угод",
        "description": "Вийдіть на регулярну активність.",
        "instructions": "Зробіть 10 угод і надішліть скрін статистики.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 500,
        "reward_description": "XP за 10 угод.",
        "icon": "fa-chart-line",
        "color": "#16a34a",
    },
    {
        "title": "Позитивний день PnL",
        "description": "Завершіть день у плюс.",
        "instructions": "Надішліть скрін PnL за день з позитивним значенням.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 10,
        "reward_description": "$10 за прибутковий день.",
        "icon": "fa-sun",
        "color": "#facc15",
    },
    {
        "title": "3 прибуткові угоди поспіль",
        "description": "Серія вдалих рішень.",
        "instructions": "Надішліть історію угод зі 3 прибутковими поспіль.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 400,
        "reward_description": "XP за вінрейт-стрик.",
        "icon": "fa-fire",
        "color": "#ef4444",
    },
    {
        "title": "Використайте стоп-лосс 3 рази",
        "description": "Дисципліна ризик-менеджменту.",
        "instructions": "Надішліть скрін 3 угод зі стоп-лосс.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 250,
        "reward_description": "XP за контроль ризику.",
        "icon": "fa-shield-alt",
        "color": "#f97316",
    },
    {
        "title": "Використайте тейк-профіт 3 рази",
        "description": "Зафіксуйте прибуток системно.",
        "instructions": "Надішліть скрін 3 угод з тейк-профіт.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 250,
        "reward_description": "XP за дисципліну фіксації прибутку.",
        "icon": "fa-flag-checkered",
        "color": "#22c55e",
    },
    {
        "title": "Налаштуйте ризик-ліміти",
        "description": "Встановіть ліміти ризику для захисту капіталу.",
        "instructions": "Налаштуйте тейк/стоп або інші ліміти. Надішліть скрін налаштувань.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за налаштування ризик-лімітів.",
        "icon": "fa-sliders-h",
        "color": "#0ea5e9",
    },
    {
        "title": "Створіть торговий журнал",
        "description": "Фіксуйте угоди та висновки.",
        "instructions": "Створіть журнал (Google Sheet/Notion) і надішліть скрін/лінк.",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за ведення журналу.",
        "icon": "fa-clipboard-list",
        "color": "#38bdf8",
    },
    {
        "title": "Поділіться скріном журналу",
        "description": "Покажіть приклад своїх записів.",
        "instructions": "Надішліть скрін/лінк на фрагмент журналу.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за демонстрацію журналу.",
        "icon": "fa-clipboard-check",
        "color": "#22c55e",
    },
    {
        "title": "Пройдіть міні-опитування",
        "description": "Допоможіть покращити продукт.",
        "instructions": "Заповніть опитування та надішліть номер/скрін підтвердження.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 100,
        "reward_description": "XP за зворотний зв'язок.",
        "icon": "fa-poll",
        "color": "#a855f7",
    },
    {
        "title": "Запропонуйте 3 ідеї покращень",
        "description": "Поділіться вашими ідеями.",
        "instructions": "Надішліть 3 пропозиції покращень у поданні.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за ідеї.",
        "icon": "fa-lightbulb",
        "color": "#facc15",
    },
    {
        "title": "Приведіть друга, що зробив 1 угоду",
        "description": "Реферал, який реально торгує.",
        "instructions": "Надішліть username реферала після його першої угоди.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 20,
        "reward_description": "$20 за активного реферала.",
        "icon": "fa-user-check",
        "color": "#22c55e",
    },
    {
        "title": "Поділіться історією успіху",
        "description": "Коротка історія результатів/досвіду.",
        "instructions": "Опублікуйте історію успіху з вашим досвідом. Надішліть лінк.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "goods",
        "reward_amount": 20,
        "reward_description": "Подарунок або доступ до івенту.",
        "icon": "fa-star",
        "color": "#f59e0b",
        "max_participants": 200,
    },
    {
        "title": "Зробіть пост у X/Twitter про MIMIC",
        "description": "Розкажіть про платформу у Twitter/X.",
        "instructions": "Опублікуйте пост з вашим досвідом і рефпосиланням. Надішліть лінк.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за публікацію.",
        "icon": "fa-twitter",
        "color": "#38bdf8",
    },
    {
        "title": "Зробіть пост в Instagram/Facebook",
        "description": "Поділіться з вашими друзями.",
        "instructions": "Опублікуйте пост/сторіз і надішліть лінк або скрін.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за публікацію.",
        "icon": "fa-camera",
        "color": "#ec4899",
    },
    {
        "title": "Залиште публічний відгук",
        "description": "Відгук на Trustpilot/Google.",
        "instructions": "Залиште відгук і надішліть лінк.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "goods",
        "reward_amount": 15,
        "reward_description": "Стікери/мерч дрібний.",
        "icon": "fa-star-half-alt",
        "color": "#f97316",
        "max_participants": 300,
    },
    {
        "title": "Пройдіть курс ризик-менеджменту",
        "description": "Навчіться керувати ризиком.",
        "instructions": "Перегляньте курс/гайд та надішліть короткий підсумок (2-3 речення).",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "subscription",
        "reward_amount": 3,
        "reward_description": "3 дні підписки за навчання.",
        "icon": "fa-graduation-cap",
        "color": "#8b5cf6",
    },
    {
        "title": "Перегляньте демо-стратегію",
        "description": "Ознайомтеся з прикладом стратегії.",
        "instructions": "Перегляньте демо-стратегію і надішліть скрін.",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за ознайомлення.",
        "icon": "fa-play-circle",
        "color": "#22c55e",
    },
    {
        "title": "Налаштуйте копіювання трейдера",
        "description": "Запустіть копіювання майстра.",
        "instructions": "Увімкніть копіювання та надішліть скрін налаштувань.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 250,
        "reward_description": "XP за запуск копіювання.",
        "icon": "fa-copy",
        "color": "#38bdf8",
    },
    {
        "title": "Спробуйте 2 різні стратегії",
        "description": "Порівняйте результати.",
        "instructions": "Активуйте 2 різні стратегії (послідовно). Надішліть скрін історії.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 250,
        "reward_description": "XP за тестування стратегій.",
        "icon": "fa-random",
        "color": "#0ea5e9",
    },
    {
        "title": "Зробіть 20 угод",
        "description": "Стабільна активність у торгівлі.",
        "instructions": "Надішліть скрін статистики з 20 угодами.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 20,
        "reward_description": "$20 за 20 угод.",
        "icon": "fa-chart-area",
        "color": "#16a34a",
    },
    {
        "title": "Запросіть 20 друзів",
        "description": "Масштабна реферальна ціль.",
        "instructions": "Надішліть список 20 usernames рефералів.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 100,
        "reward_description": "$100 за 20 рефералів.",
        "icon": "fa-users",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 30 друзів",
        "description": "Топовий реферальний рівень.",
        "instructions": "Надішліть список 30 usernames рефералів.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "goods",
        "reward_amount": 50,
        "reward_description": "Подарунок/мерч на $50.",
        "icon": "fa-users",
        "color": "#14b8a6",
    },
    {
        "title": "Запросіть 50 друзів",
        "description": "Елітна реферальна нагорода.",
        "instructions": "Надішліть список 50 usernames рефералів.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "subscription",
        "reward_amount": 30,
        "reward_description": "30 днів підписки за 50 рефералів.",
        "icon": "fa-crown",
        "color": "#fbbf24",
    },
    {
        "title": "Проведіть міні-зустріч для друзів",
        "description": "Міні-онбординг для новачків.",
        "instructions": "Проведіть міні-дзвінок/зустріч та надішліть короткий звіт.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "goods",
        "reward_amount": 30,
        "reward_description": "Подарунок або доступ до івенту.",
        "icon": "fa-users-cog",
        "color": "#f97316",
        "max_participants": 100,
    },
    {
        "title": "Напишіть гайд для новачків",
        "description": "Поділіться досвідом для нових користувачів.",
        "instructions": "Напишіть гайд (5-10 пунктів) і надішліть документ/лінк.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "goods",
        "reward_amount": 40,
        "reward_description": "Подарунок/мерч на $40.",
        "icon": "fa-pen-nib",
        "color": "#a855f7",
        "max_participants": 100,
    },
    {
        "title": "Активність у чаті 7 днів",
        "description": "Спілкування та підтримка спільноти.",
        "instructions": "Напишіть щонайменше 1 корисне повідомлення щодня протягом 7 днів. Додайте скрін/посилання.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за активність у чаті.",
        "icon": "fa-comments",
        "color": "#38bdf8",
    },
    {
        "title": "Перевірте налаштування API безпеки",
        "description": "Переконайтесь, що немає прав на виведення.",
        "instructions": "Надішліть скрін налаштувань API (без секретів).",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за перевірку безпеки.",
        "icon": "fa-key",
        "color": "#f97316",
    },
    {
        "title": "Додайте email для відновлення",
        "description": "Важливо для відновлення доступу.",
        "instructions": "Додайте email і надішліть скрін налаштувань.",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 100,
        "reward_description": "XP за додавання email.",
        "icon": "fa-envelope",
        "color": "#60a5fa",
    },
    {
        "title": "Виконайте 3 навчальні угоди",
        "description": "Практика без ризику великих сум.",
        "instructions": "Зробіть 3 невеликі угоди та надішліть скрін історії.",
        "task_type": "trading",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за навчальні угоди.",
        "icon": "fa-graduation-cap",
        "color": "#22c55e",
    },
    {
        "title": "Візьміть участь у голосуванні",
        "description": "Впливайте на майбутні зміни.",
        "instructions": "Проголосуйте в опитуванні та надішліть скрін.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 100,
        "reward_description": "XP за участь у голосуванні.",
        "icon": "fa-vote-yea",
        "color": "#a855f7",
    },
    {
        "title": "Запросіть 1 друга та отримайте його відгук",
        "description": "Запросіть друга і зберіть фідбек.",
        "instructions": "Надішліть username друга та його короткий відгук.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "goods",
        "reward_amount": 15,
        "reward_description": "Подарунок/стікери за фідбек.",
        "icon": "fa-comment",
        "color": "#f97316",
    },
    {
        "title": "Пройдіть онбординг-тур платформи",
        "description": "Ознайомтесь з основними розділами.",
        "instructions": "Пройдіть тур/скрол до ключових секцій і надішліть скрін.",
        "task_type": "custom",
        "category": "Onboarding",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за проходження туру.",
        "icon": "fa-compass",
        "color": "#38bdf8",
        "is_featured": True,
    },
    {
        "title": "Оновіть пароль на унікальний",
        "description": "Підвищте безпеку акаунту.",
        "instructions": "Змініть пароль на унікальний та надішліть скрін підтвердження.",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за оновлення паролю.",
        "icon": "fa-key",
        "color": "#f59e0b",
    },
    {
        "title": "Перевірте історію входів",
        "description": "Переконайтесь, що немає підозрілих входів.",
        "instructions": "Відкрийте розділ безпеки та надішліть скрін.",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 100,
        "reward_description": "XP за перевірку безпеки.",
        "icon": "fa-user-shield",
        "color": "#f97316",
    },
    {
        "title": "Додайте резервний контакт для відновлення",
        "description": "Резервний контакт допоможе відновити доступ.",
        "instructions": "Додайте резервний контакт і надішліть скрін.",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за резервний контакт.",
        "icon": "fa-phone",
        "color": "#60a5fa",
    },
    {
        "title": "Увімкніть push-сповіщення в браузері",
        "description": "Будьте в курсі подій у режимі реального часу.",
        "instructions": "Увімкніть push-сповіщення і надішліть скрін.",
        "task_type": "custom",
        "category": "Onboarding",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за увімкнення сповіщень.",
        "icon": "fa-bell",
        "color": "#0ea5e9",
    },
    {
        "title": "Ознайомтесь з розділом підписок",
        "description": "Дізнайтесь про тарифи та можливості.",
        "instructions": "Відкрийте підписки та надішліть скрін.",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 80,
        "reward_description": "XP за ознайомлення з підписками.",
        "icon": "fa-crown",
        "color": "#8b5cf6",
    },
    {
        "title": "Відкрийте сторінку лідерборду",
        "description": "Перегляньте топ трейдерів.",
        "instructions": "Зайдіть у лідерборд та надішліть скрін.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 80,
        "reward_description": "XP за активність.",
        "icon": "fa-trophy",
        "color": "#f59e0b",
    },
    {
        "title": "Надішліть перше повідомлення адміну",
        "description": "Познайомтесь з командою підтримки.",
        "instructions": "Надішліть коротке повідомлення у чат підтримки.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за перший контакт.",
        "icon": "fa-envelope-open",
        "color": "#38bdf8",
    },
    {
        "title": "Дайте фідбек про інтерфейс",
        "description": "Що можна покращити?",
        "instructions": "Надішліть 2-3 пункти фідбеку.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за фідбек.",
        "icon": "fa-desktop",
        "color": "#0ea5e9",
    },
    {
        "title": "Підготуйте 3 запитання для Q&A",
        "description": "Зберемо питання для наступного ефіру.",
        "instructions": "Напишіть 3 запитання для Q&A.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за запитання.",
        "icon": "fa-question-circle",
        "color": "#a855f7",
    },
    {
        "title": "Підготуйте 3 поради для новачків",
        "description": "Допоможіть новим користувачам.",
        "instructions": "Напишіть 3 поради та надішліть.",
        "task_type": "community",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за поради.",
        "icon": "fa-hands-helping",
        "color": "#22c55e",
    },
    {
        "title": "Опублікуйте пост у LinkedIn",
        "description": "Поділіться професійним кейсом.",
        "instructions": "Опублікуйте пост та надішліть лінк.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 250,
        "reward_description": "XP за LinkedIn-пост.",
        "icon": "fa-linkedin",
        "color": "#0ea5e9",
    },
    {
        "title": "Публікація у Reddit/форумі",
        "description": "Поділіться досвідом у тематичній спільноті.",
        "instructions": "Опублікуйте пост без спаму та надішліть лінк.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 220,
        "reward_description": "XP за публікацію на форумі.",
        "icon": "fa-reddit",
        "color": "#f97316",
    },
    {
        "title": "Поділіться сторіз про MIMIC",
        "description": "Коротке сторіз для ваших підписників.",
        "instructions": "Опублікуйте сторіз і надішліть скрін.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за сторіз.",
        "icon": "fa-camera",
        "color": "#ec4899",
    },
    {
        "title": "Поділіться реферальним кодом у статусі профілю",
        "description": "Додайте рефкод у статус/біо.",
        "instructions": "Додайте рефкод і надішліть скрін.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за рефкод у біо.",
        "icon": "fa-id-card",
        "color": "#38bdf8",
    },
    {
        "title": "Запишіть аудіо-відгук (30-60 сек)",
        "description": "Короткий аудіо-відгук про платформу.",
        "instructions": "Запишіть аудіо та надішліть лінк/файл.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "goods",
        "reward_amount": 20,
        "reward_description": "Подарунок/стікери.",
        "icon": "fa-microphone",
        "color": "#f97316",
        "max_participants": 150,
    },
    {
        "title": "Опублікуйте відео-огляд на YouTube/Shorts",
        "description": "Відео 30-60 секунд.",
        "instructions": "Опублікуйте відео та надішліть лінк.",
        "task_type": "social",
        "category": "Social",
        "reward_type": "goods",
        "reward_amount": 35,
        "reward_description": "Подарунок/мерч за відео.",
        "icon": "fa-youtube",
        "color": "#ef4444",
        "max_participants": 150,
    },
    {
        "title": "Опублікуйте огляд функцій (5-7 пунктів)",
        "description": "Короткий огляд ключових функцій.",
        "instructions": "Напишіть огляд і надішліть лінк.",
        "task_type": "community",
        "category": "Education",
        "reward_type": "goods",
        "reward_amount": 30,
        "reward_description": "Подарунок/доступ до івенту.",
        "icon": "fa-clipboard",
        "color": "#f59e0b",
        "max_participants": 200,
    },
    {
        "title": "Оформіть міні-кейс (1-2 абзаци)",
        "description": "Кейс з вашим підходом.",
        "instructions": "Опишіть кейс і надішліть у поданні.",
        "task_type": "community",
        "category": "Education",
        "reward_type": "goods",
        "reward_amount": 25,
        "reward_description": "Подарунок за кейс.",
        "icon": "fa-file-alt",
        "color": "#f59e0b",
        "max_participants": 200,
    },
    {
        "title": "Поділіться досвідом у коментарях",
        "description": "Короткий коментар у спільноті.",
        "instructions": "Залиште корисний коментар і надішліть посилання.",
        "task_type": "community",
        "category": "Community",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за коментар.",
        "icon": "fa-comment",
        "color": "#38bdf8",
    },
    {
        "title": "Перегляньте політику ризиків і надішліть 2 висновки",
        "description": "Підвищимо усвідомленість ризиків.",
        "instructions": "Напишіть 2 висновки після ознайомлення.",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 120,
        "reward_description": "XP за усвідомлення ризиків.",
        "icon": "fa-exclamation-triangle",
        "color": "#f59e0b",
    },
    {
        "title": "Пройдіть тест з безпеки акаунту",
        "description": "Міні‑тест із 5 питань.",
        "instructions": "Пройдіть тест і надішліть скрін результату.",
        "task_type": "custom",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за тест з безпеки.",
        "icon": "fa-user-shield",
        "color": "#f97316",
    },
    {
        "title": "Складіть план торгівлі на день",
        "description": "Сформуйте простий план на день.",
        "instructions": "Надішліть 3-5 пунктів плану.",
        "task_type": "custom",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за планування.",
        "icon": "fa-map",
        "color": "#a855f7",
    },
    {
        "title": "Зробіть 1 угоду лімітним ордером",
        "description": "Практика лімітних ордерів.",
        "instructions": "Надішліть скрін історії угод.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за лімітний ордер.",
        "icon": "fa-layer-group",
        "color": "#22c55e",
    },
    {
        "title": "Зробіть 1 угоду маркет-ордером",
        "description": "Практика ринкових ордерів.",
        "instructions": "Надішліть скрін історії угод.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за маркет-ордер.",
        "icon": "fa-bolt",
        "color": "#22c55e",
    },
    {
        "title": "Зробіть 2 угоди в різних парах",
        "description": "Диверсифікуйте торгові пари.",
        "instructions": "Надішліть скрін історії.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за різні пари.",
        "icon": "fa-exchange-alt",
        "color": "#22c55e",
    },
    {
        "title": "Зробіть 2 угоди LONG/SHORT",
        "description": "Спробуйте різні напрями.",
        "instructions": "Надішліть скрін 2 угод.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за LONG/SHORT.",
        "icon": "fa-arrows-alt-v",
        "color": "#22c55e",
    },
    {
        "title": "Зробіть 15 угод",
        "description": "Регулярність торгівлі.",
        "instructions": "Надішліть скрін статистики.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 15,
        "reward_description": "$15 за 15 угод.",
        "icon": "fa-chart-line",
        "color": "#16a34a",
    },
    {
        "title": "Зробіть 30 угод",
        "description": "Стабільна активність.",
        "instructions": "Надішліть скрін статистики.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 30,
        "reward_description": "$30 за 30 угод.",
        "icon": "fa-chart-area",
        "color": "#16a34a",
    },
    {
        "title": "Зробіть 50 угод",
        "description": "Висока активність.",
        "instructions": "Надішліть скрін статистики.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 60,
        "reward_description": "$60 за 50 угод.",
        "icon": "fa-chart-bar",
        "color": "#16a34a",
    },
    {
        "title": "Зробіть 5 угод за тиждень",
        "description": "Тижневий челендж.",
        "instructions": "Надішліть скрін історії.",
        "task_type": "trading",
        "category": "Retention",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за тижневу активність.",
        "icon": "fa-calendar-week",
        "color": "#38bdf8",
    },
    {
        "title": "Позитивний тиждень PnL",
        "description": "Завершіть тиждень у плюс.",
        "instructions": "Надішліть скрін PnL.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "money",
        "reward_amount": 20,
        "reward_description": "$20 за позитивний тиждень.",
        "icon": "fa-sun",
        "color": "#facc15",
    },
    {
        "title": "Налаштуйте ліміт кредитного плеча",
        "description": "Контроль ризиків.",
        "instructions": "Встановіть ліміт та надішліть скрін.",
        "task_type": "trading",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 160,
        "reward_description": "XP за ліміти плеча.",
        "icon": "fa-sliders-h",
        "color": "#f59e0b",
    },
    {
        "title": "Налаштуйте шаблон ризику (take/stop)",
        "description": "Системний підхід до ризику.",
        "instructions": "Налаштуйте тейк/стоп і надішліть скрін.",
        "task_type": "trading",
        "category": "Security",
        "reward_type": "xp",
        "reward_amount": 160,
        "reward_description": "XP за шаблон ризику.",
        "icon": "fa-shield-alt",
        "color": "#f97316",
    },
    {
        "title": "Поділіться скріном налаштувань стратегії",
        "description": "Покажіть налаштування стратегії.",
        "instructions": "Надішліть скрін налаштувань.",
        "task_type": "trading",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 150,
        "reward_description": "XP за налаштування стратегії.",
        "icon": "fa-cogs",
        "color": "#38bdf8",
    },
    {
        "title": "Підключіть другу біржу",
        "description": "Додайте ще одну біржу.",
        "instructions": "Підключіть біржу і надішліть скрін.",
        "task_type": "trading",
        "category": "Trading",
        "reward_type": "xp",
        "reward_amount": 300,
        "reward_description": "XP за другу біржу.",
        "icon": "fa-network-wired",
        "color": "#22c55e",
    },
    {
        "title": "Оновіть стратегію раз на місяць",
        "description": "Регулярне оновлення налаштувань.",
        "instructions": "Оновіть параметри і надішліть скрін.",
        "task_type": "trading",
        "category": "Retention",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за оновлення стратегії.",
        "icon": "fa-sync",
        "color": "#38bdf8",
    },
    {
        "title": "Запросіть 2 друзів у Telegram",
        "description": "Підсилення спільноти.",
        "instructions": "Надішліть usernames двох друзів.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за Telegram-запрошення.",
        "icon": "fa-telegram-plane",
        "color": "#0ea5e9",
    },
    {
        "title": "Запросіть 7 друзів",
        "description": "Реферальний крок.",
        "instructions": "Надішліть список 7 usernames.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 35,
        "reward_description": "$35 за 7 рефералів.",
        "icon": "fa-users",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 12 друзів",
        "description": "Реферальний рівень.",
        "instructions": "Надішліть список 12 usernames.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 60,
        "reward_description": "$60 за 12 рефералів.",
        "icon": "fa-users",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 25 друзів",
        "description": "Серйозний ріст.",
        "instructions": "Надішліть список 25 usernames.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 150,
        "reward_description": "$150 за 25 рефералів.",
        "icon": "fa-users",
        "color": "#22c55e",
        "max_participants": 100,
    },
    {
        "title": "Запросіть 40 друзів",
        "description": "Високий рівень залучення.",
        "instructions": "Надішліть список 40 usernames.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "subscription",
        "reward_amount": 20,
        "reward_description": "20 днів підписки.",
        "icon": "fa-crown",
        "color": "#fbbf24",
    },
    {
        "title": "Запросіть 2 друзів, що підключили біржу",
        "description": "Запросіть друзів, які підключать біржу.",
        "instructions": "Надішліть usernames двох друзів після підключення.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 30,
        "reward_description": "$30 за 2 підключення.",
        "icon": "fa-link",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 1 друга, який зробив 5 угод",
        "description": "Активний реферал.",
        "instructions": "Надішліть username після 5 угод.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "money",
        "reward_amount": 25,
        "reward_description": "$25 за активного реферала.",
        "icon": "fa-user-check",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 3 друзів на вебінар",
        "description": "Запросіть друзів на навчання.",
        "instructions": "Надішліть usernames та підтвердження участі.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за запрошення на вебінар.",
        "icon": "fa-video",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 1 друга на демо-сесію",
        "description": "Покажіть платформу у дії.",
        "instructions": "Проведіть демо і надішліть короткий звіт.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "xp",
        "reward_amount": 200,
        "reward_description": "XP за демо-сесію.",
        "icon": "fa-chalkboard-teacher",
        "color": "#22c55e",
    },
    {
        "title": "Запросіть 5 друзів у спільноту",
        "description": "Розширте спільноту.",
        "instructions": "Надішліть usernames 5 друзів.",
        "task_type": "referral",
        "category": "Referral",
        "reward_type": "xp",
        "reward_amount": 300,
        "reward_description": "XP за 5 учасників.",
        "icon": "fa-users",
        "color": "#22c55e",
    },
    {
        "title": "Зробіть 5 днів активності поспіль",
        "description": "Регулярність користування.",
        "instructions": "Надішліть скрін/опис активності.",
        "task_type": "custom",
        "category": "Retention",
        "reward_type": "xp",
        "reward_amount": 160,
        "reward_description": "XP за регулярність.",
        "icon": "fa-calendar-check",
        "color": "#22c55e",
    },
    {
        "title": "Поділіться чеклістом входу в угоду",
        "description": "Покажіть ваш підхід.",
        "instructions": "Надішліть 3-5 пунктів чекліста.",
        "task_type": "community",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 160,
        "reward_description": "XP за чекліст.",
        "icon": "fa-list-check",
        "color": "#38bdf8",
    },
    {
        "title": "Оформіть аналіз 1 угоди",
        "description": "Розбір однієї угоди.",
        "instructions": "Опишіть коротко, чому увійшли/вийшли.",
        "task_type": "community",
        "category": "Education",
        "reward_type": "xp",
        "reward_amount": 180,
        "reward_description": "XP за аналіз угоди.",
        "icon": "fa-search",
        "color": "#a855f7",
    },
]


def seed_tasks(limit=None, dry_run=False):
    with app.app_context():
        admin_user = User.query.filter_by(role="admin").first()
        created_by_id = admin_user.id if admin_user else None
        now = datetime.now(timezone.utc)

        created = 0
        skipped = 0
        task_list = TASKS[:limit] if limit else TASKS

        for task_data in task_list:
            title = task_data["title"]
            if Task.query.filter_by(title=title).first():
                skipped += 1
                continue

            task = Task(
                title=title,
                description=task_data.get("description", ""),
                instructions=task_data.get("instructions", ""),
                task_type=task_data.get("task_type", "custom"),
                category=task_data.get("category"),
                icon=task_data.get("icon", "fa-tasks"),
                color=task_data.get("color", "#00f5ff"),
                reward_type=task_data.get("reward_type", "money"),
                reward_amount=float(task_data.get("reward_amount", 0)),
                reward_description=task_data.get("reward_description"),
                max_participants=task_data.get("max_participants"),
                max_completions_per_user=int(task_data.get("max_completions_per_user", 1)),
                requires_approval=task_data.get("requires_approval", True),
                status=task_data.get("status", "active"),
                is_featured=task_data.get("is_featured", False),
                created_by_id=created_by_id,
                created_at=now,
            )

            db.session.add(task)
            created += 1

        if dry_run:
            db.session.rollback()
        else:
            db.session.commit()

        return created, skipped


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed engagement tasks for 2026 growth.")
    parser.add_argument("--dry-run", action="store_true", help="Do not write to the database.")
    parser.add_argument("--limit", type=int, default=None, help="Only create the first N tasks.")
    args = parser.parse_args()

    created_count, skipped_count = seed_tasks(limit=args.limit, dry_run=args.dry_run)
    mode = "DRY RUN" if args.dry_run else "CREATED"
    print(f"{mode}: {created_count} tasks, skipped {skipped_count} existing.")
